export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_CORRECT = "ADD_PRODUCT_CORRECT";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const INIT_DOWNLOAD_PRODUCTS = "INIT_DOWNLOAD_PRODUCTS";
export const DOWNLOAD_PRODUCTS_CORRECT = "DOWNLOAD_PRODUCTS_CORRECT";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR";

export const GET_PRODUCT_DELETE = "GET_PRODUCT_DELETE";
export const GET_DELETE_CORRECT = "GET_DELETE_CORRECT";
export const GET_DELETE_ERROR = "GET_DELETE_ERROR";

export const GET_PRODUCT_ACTIVE = "GET_PRODUCT_ACTIVE";
export const START_PRODUCT_EDIT = "START_PRODUCT_EDIT";
export const GET_EDIT_CORRECT = "GET_EDIT_CORRECT";
export const GET_EDIT_ERROR = "GET_EDIT_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDDEN_ALERT = "HIDDEN_ALERT";
